# Notes from [Machine Learning Foundations: Linear Algebra](https://www.linkedin.com/learning/machine-learning-foundations-linear-algebra)

In [1]:
import numpy as np

## Vector Basics

### Vector Arithmetic

In [2]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

In [3]:
a + b

array([30, 60, 90])

In [4]:
# Causes an error since dimensions don't match 
# a + c

In [5]:
a - b

array([10, 20, 30])

In [6]:
# Causes an error since dimensions don't match 
# a - c 

In [7]:
a * b

array([ 200,  800, 1800])

In [8]:
a / b

array([2., 2., 2.])

In [9]:
scalar = 2

In [10]:
list_a = [10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [11]:
list_as_array = np.array(list_a) 
print(list_as_array)

[10 11 12 13 14 15]


In [12]:
# Prints twice 
scalar * list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [13]:
# Multiplies each cell by value
scalar * list_as_array

array([20, 22, 24, 26, 28, 30])

## Vector Projections and Bias

### Dot product of vectors

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [15]:
np.dot(a, b)

130

In [16]:
np.dot(b,a)

130

In [17]:
c = np.array([11,12,13,14,15])

In [18]:
first_result = np.dot(a, b+c)
print(first_result)

335


In [19]:
second_result = np.dot(a,b) + np.dot(a, c)
print(second_result)

335


### Scalar and vector projection

In [20]:
from numpy import linalg as lng

In [21]:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

lng.norm(a)

74.16198487095663

In [22]:
vector_projection = (np.dot(a,b) / np.dot(b,b)) * b
print(vector_projection)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]


## Gaussian Elimination

### Steps
1. Converting system to matrix-vector equation
2. Augmenting the coefficient matrix with the vector of constants
3. Creating a matrix with ones on diagonals
4. Mapping the matrix back to equations
5. Substitution to solve for variables

In [23]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [24]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
b = np.array([5,11])
b

array([ 5, 11])

In [26]:
x = np.dot(Ainv,b)
x

array([1., 2.])

In [27]:
np.dot(A,x)

array([ 5., 11.])

### Inverse and determinant

In [28]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [29]:
det = np.linalg.det(A)
det

-2.0000000000000004

In [30]:
B = np.array([[3,1],[6,2]])
B

array([[3, 1],
       [6, 2]])

In [31]:
np.linalg.det(B)

0.0

In [33]:
# Errors: cannot calculate inverse of singular matrix
# np.linalg.inv(B)