# Notes from [Machine Learning Foundations: Linear Algebra](https://www.linkedin.com/learning/machine-learning-foundations-linear-algebra)

In [182]:
import numpy as np

## Vector Basics

### Vector Arithmetic

In [183]:
a = np.array([20,40,60])
b = np.array([10,20,30])
c = np.array([5,10,15,20])

In [184]:
a + b

array([30, 60, 90])

In [185]:
# Causes an error since dimensions don't match 
# a + c

In [186]:
a - b

array([10, 20, 30])

In [187]:
# Causes an error since dimensions don't match 
# a - c 

In [188]:
a * b

array([ 200,  800, 1800])

In [189]:
a / b

array([2., 2., 2.])

In [190]:
scalar = 2

In [191]:
list_a = [10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [192]:
list_as_array = np.array(list_a) 
print(list_as_array)

[10 11 12 13 14 15]


In [193]:
# Prints twice 
scalar * list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [194]:
# Multiplies each cell by value
scalar * list_as_array

array([20, 22, 24, 26, 28, 30])

## Vector Projections and Bias

### Dot product of vectors

In [195]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [196]:
np.dot(a, b)

130

In [197]:
np.dot(b,a)

130

In [198]:
c = np.array([11,12,13,14,15])

In [199]:
first_result = np.dot(a, b+c)
print(first_result)

335


In [200]:
second_result = np.dot(a,b) + np.dot(a, c)
print(second_result)

335


### Scalar and vector projection

In [201]:
from numpy import linalg as lng

In [202]:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

lng.norm(a)

74.16198487095663

In [203]:
vector_projection = (np.dot(a,b) / np.dot(b,b)) * b
print(vector_projection)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]


## 